name: Rust CI
on:
  push:
    branches: [master, legacy/v0.1.0]
  pull_request:
    branches: [master, legacy/v0.1.0]
permissions:
  contents: read
  pages: write
  id-token: write
env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: stable

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt, clippy
      - name: Configure cache
        uses: Swatinem/rust-cache@v2
      
      - name: Run fmt
        run: cargo fmt --all -- --check
      - name: Run clippy
        run: cargo clippy --all-features

      - name: Run tests
        run: cargo test --all-features

      - name: Clean docs folder
        run: cargo clean --doc

      - name: Build docs
        run: cargo doc --no-deps
      
