name: Rust CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
permissions:
  contents: read
  pages: write
  id-token: write
env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Configure cache
        uses: Swatinem/rust-cache@v2
      - name: Clean docs folder
        run: cargo clean --doc
      - name: Build docs
        run: cargo doc --no-deps
